id: I798E3E28
legacy_id: P010426
ocr_import_info:
  bdrc_scan_id: W7371
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T03:01:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:12:02.921766+00:00'
last_modified: 2022-09-04 11:12:18.461723
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W7371
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW7371
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀྲ་ཤིས་ལྷུན་པོའི་རྒྱུད་པ་གྲྭ་ཚང་གི་གདན་རབས་སོགས།
  author: པཎ་ཆེན་བསོད་ནམས་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.7827752372870456
  ocr_word_median_confidence_index: 0.8399999737739563
quality: null
bases:
  I1KG9118:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9118
      total_pages: 455
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9118.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7827752372870456
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
