id: P010426
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:49:18.738072
source_metadata:
  id: bdr:W7371
  title: བཀྲ་ཤིས་ལྷུན་པོའི་རྒྱུད་པ་གྲྭ་ཚང་གི་གདན་རབས་སོགས།
  author: ''
  volumes:
    a9b6d77dccad44919513d5e6499917b6:
      image_group_id: I1KG9118
      title: ''
      volume_number: 1
      total_pages: 455
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
